# Generated by Django 5.2.4 on 2025-08-04 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='To')),
                ('subject', models.CharField(max_length=200)),
                ('scheduled_time', models.DateTimeField(verbose_name='Time')),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
